# fly.toml app configuration file generated for hidden-water-4767 on 2023-09-07T14:29:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hidden-water-4767"
primary_region = "ewr"

# kill_signal = "SIGINT" 
# kill_timeout = 5

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[http_service]
  internal_port = 8080
  force_https = true

  # Auto-start and stop should have the same value.
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
    grace_period = "10s"
    internal = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health_check"
