unstable_features = true
max_width = 80
imports_granularity = "Item"
wrap_comments = true
doc_comment_code_block_width = 80
format_code_in_doc_comments = true
format_strings = true
normalize_comments = true
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
reorder_impl_items = true