doc_comment_code_block_width = 80
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
max_width = 80
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
unstable_features = true
wrap_comments = true